apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  template:
    secret:
      metadata:
        labels:
          label1: value1
        annotations:
          anno1: value1